### ISSUE TITLE
Clarification Needed on Contribution Guidelines

### ISSUE THREAD

**Issue by Rufusemmanuel** [Consensys/linea-monorepo#254]
## Description

I noticed a couple of areas in the contribution guidelines that could benefit from clarification:

Tagging Maintainers: In the "How to contribute" section, it mentions tagging for discussion if the update is non-trivial. It would be helpful to specify who should be tagged (e.g., specific maintainers or teams).

Inconsistency in Terminology: The document uses both "repo" and "repository." For consistency and clarity, it would be better to standardize on one term throughout the document.

## Motivation
Consistency and clarity of the contribution guidelines document 

 Proposed Solution:

For the tagging issue, consider adding a specific mention of who to tag in the contribution guidelines. For the terminology inconsistency, I can submit a pull request to standardize on "repository."

**Comment by Rufusemmanuel** [comment]
@jpnovais @VGau please this PR is ready to be merged

**Comment by jpnovais** [comment]
Thanks for raising that @Rufusemmanuel and the PR. 

I would suggest tagging teams instead of individual contributors (it scales better). Also, I would suggest to  create the tag handles for high lever subject/matters and add that mapping to the section. @julien-marchand WDYT?

**Comment by Rufusemmanuel** [comment]
That is the problem, we do not know the individuals to tag directly
